<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_01</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d506069c-7c8e-4d19-992a-ea0af36fc90a</testSuiteGuid>
   <testCaseLink>
      <guid>465d2c69-b250-41b8-8bb7-c4ce7e54ad72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a32bc29-f902-4a04-b983-9a247c660cc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bd49373-6234-4c18-82a0-62cbc52e719c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a58b6107-f324-473c-a499-036f84b96608</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11235644-3eaa-4ff4-be02-397cdf4572e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e5e8911-275d-471e-97db-f23f4c719978</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2e94917-3008-4b21-b6e4-242996482e9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46202012-7522-4aa1-a753-427dbe90d2af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb1efefb-a48a-45a3-8e4a-2c9a52003f86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f3ef3e5-2679-42d5-b3a3-7a4a54048bac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9c7c22f-e65d-411f-b5e9-1c2a1028693f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7189dc52-6e3f-43d6-a1b7-1d477895543d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f451f66-64a7-419d-9e14-e9f4d5e3bb4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase5</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7be4a41-a979-4cb8-b865-42cd3c9b1996</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a71d094c-bca6-4461-b684-3cec74fa9280</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
