<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_03</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>acf94642-6048-4022-9da1-794e3142f412</testSuiteGuid>
   <testCaseLink>
      <guid>41ca610c-5dbe-465b-8586-e7c1b17731d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1534d89-1f5d-4e45-b615-7685adf66fd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b559756-6f4b-4586-9bb0-a9b140f05530</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c7a42e5-389e-4650-b974-939521968a47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42e19c49-e825-43b0-8331-2ebd467e2617</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ce1b9a3-761c-434f-a144-1c6f07c3288b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e52ab36-aebe-4866-bb8e-74c9f3c2c053</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffc4c17d-4db4-4686-a33e-47500be23de3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c5cf22f-53f5-4865-8280-1e3de0e7cfc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee7cc43e-3443-435f-bc2c-e57acc4b6e59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22f68bb3-102b-46c0-b978-ea8bc6e6a542</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee7755ea-90ad-4605-9681-3b74adabd348</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d3fa057-7858-4fdc-b31b-c36fc97f0f9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HRIS/SignIn/testcase15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5d291fc-632e-476e-adcb-07280c6d90d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1371f519-a275-4177-978c-0358206773c9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
