<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5</name>
   <tag></tag>
   <elementGuidId>aafa93e5-ca11-46d9-8a4b-d4a843cb5664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.nav.child_menu > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-menu']/div/ul/li[3]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Employees&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1008f22c-2d43-49e9-884e-08586c15bfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qahris.trilasoft.com/graph/employees</value>
      <webElementGuid>7f54d144-2ac4-40d8-acad-680e07304965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employees</value>
      <webElementGuid>e8b9b7ef-5ab8-4490-bfb6-f9ed0e933aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-menu&quot;)/div[@class=&quot;menu_section active&quot;]/ul[@class=&quot;nav side-menu&quot;]/li[@class=&quot;active&quot;]/ul[@class=&quot;nav child_menu&quot;]/li[2]/a[1]</value>
      <webElementGuid>beb4bf77-10d8-4ee8-8427-936890929628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-menu']/div/ul/li[3]/ul/li[2]/a</value>
      <webElementGuid>c5159ab0-dd33-47b6-959b-23b7e1329a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Employees')]</value>
      <webElementGuid>756bc619-cfed-40cd-84a2-be7e13f0c17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Managers'])[1]/following::a[1]</value>
      <webElementGuid>b1767f0e-7ac8-4967-b962-76a39b3dd38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statistics'])[1]/following::a[2]</value>
      <webElementGuid>1a38e08a-a7fd-4f6c-9d55-d58b23ce8ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaves'])[1]/preceding::a[1]</value>
      <webElementGuid>f9399999-2bf7-4fcb-b45a-b2eab47df562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[1]/preceding::a[2]</value>
      <webElementGuid>1c1c5ef3-7a77-4d61-8e30-250be3eec2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employees']/parent::*</value>
      <webElementGuid>9f7ebf76-53a8-49df-97b8-6ac77d3b4f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://qahris.trilasoft.com/graph/employees')]</value>
      <webElementGuid>5bc712b1-2469-4c9d-ac28-007bc7b2294c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/a</value>
      <webElementGuid>182c9add-6da7-4ce4-b147-1bfc2a792362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://qahris.trilasoft.com/graph/employees' and (text() = 'Employees' or . = 'Employees')]</value>
      <webElementGuid>e5e2eb0b-6821-4742-8101-45bcaab4d321</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
