<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_India_commonModal__close</name>
   <tag></tag>
   <elementGuidId>ab123fe3-e0f8-4278-b15a-61c6233a3b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SW']/div/div[2]/div[2]/div/section/span_wrng</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.commonModal__close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section >> internal:has-text=&quot;Personal AccountMyBiz Account Mobile Number ‎+91Continue Or Login/Signup With By&quot;i >> span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a0e9163-f800-4edf-8c1d-c81fdae6a19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>closeModal</value>
      <webElementGuid>859fa69a-d101-4b3f-bcc8-49d662a745ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>commonModal__close</value>
      <webElementGuid>58dfc401-904b-4626-b6fd-7bc1a49caff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SW&quot;)/div[@class=&quot;landingContainer eng&quot;]/div[@class=&quot;headerOuter&quot;]/div[@class=&quot;imageSliderModal modal displayBlock modalLogin dynHeight personal&quot;]/div[@class=&quot;imageSlideContainer&quot;]/section[@class=&quot;modalMain tcnFooter&quot;]/span[@class=&quot;commonModal__close&quot;]</value>
      <webElementGuid>c9c935ec-5265-4860-b68b-be666fd14b45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SW']/div/div[2]/div[2]/div/section/span_wr@@@@@@@@ong</value>
      <webElementGuid>5d702fbc-07a1-417a-83af-56c596ea5595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/span</value>
      <webElementGuid>ca14ac70-e304-41d4-ad2f-c7cdebd5fea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
